const Notification = require('../models/Notification');

// أنواع الإشعارات التلقائية
const AUTO_NOTIFICATIONS = {
    BUDGET_EXCEEDED: {
        title: 'تجاوز الميزانية',
        type: 'warning'
    },
    LOW_BALANCE: {
        title: 'رصيد منخفض',
        type: 'danger'
    },
    MONTHLY_SUMMARY: {
        title: 'ملخص شهري',
        type: 'info'
    }
};

// إنشاء إشعار تلقائي
const createAutoNotification = async (userId, notificationType, message, relatedEntity = null, entityId = null) => {
    try {
        const { title, type } = AUTO_NOTIFICATIONS[notificationType];
        
        await Notification.create({
            userId,
            title,
            message,
            type,
            relatedEntity,
            entityId,
            isAutoGenerated: true
        });
    } catch (error) {
        console.error('فشل إنشاء إشعار تلقائي:', error);
    }
};

module.exports = {
    createAutoNotification
};